services:
  mysql-server:
    image: mysql:8.3.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: mydb
  redis-session-store:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
